### ISSUE TITLE
Cannot install composer 

### ISSUE THREAD

**Issue by TheWolds** [doxadoxa/phpethaddress#1]
The error 

`[InvalidArgumentException]                                                                                               
  Could not find a version of package doxadoxa/phpethaddress matching your minimum-stability (stable). Require it with an  
   explicit version constraint allowing its desired stability.     `

**Comment by doxadoxa** [comment]
Hey! You need to change minimal-stability in your project composer.json file from stable to dev.

**Comment by TheWolds** [comment]
> Hey! You need to change minimal-stability in your project composer.json file from stable to dev.

Thank you so much for the speedy reply, your code is perfect , but sometime is have an error and i dont known why.
I have noticed when `$publicKeyHex` have 127 characters , it will errror , and i try to debug :
![1](https://user-images.githubusercontent.com/51010476/59341223-adc82600-8d31-11e9-8bfa-d2a88bae7d7d.png)
![2](https://user-images.githubusercontent.com/51010476/59341224-adc82600-8d31-11e9-9420-5804e994fc03.png)

**Comment by TheWolds** [comment]
When error , the `privateKey` is invaild with `publicKey`

Here is result for test : 
publicKey: `0xdcc703c0e500b653ca82273b7bfad8045d85a470`
privateKey: `2e0873d9f0bb1d2e8242b72e6816771b5ae6f79efabccd8638cca1ffa4b1c2`
